all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    ci:
      hosts:
        ci_hosting:
          ansible_ssh_private_key_file: /Users/eugene/Dropbox/Eugene/Backups/agile-practices-dev.pem #TODO Set path to private key .pem file for CI host
          ansible_host: 84.201.134.115 #TODO Set CI hosting hostname
          ansible_user: admin #TODO Set CI host username for Ansible provisioning
        ci_agent:
          ansible_ssh_private_key_file: /Users/eugene/Dropbox/Eugene/Backups/agile-practices-dev.pem #TODO Set path to private key .pem file for CI host
          ansible_host: 84.201.134.115 #TODO Set CI hosting hostname
          ansible_user: admin #TODO Set CI host username for Ansible provisioning
        pre_prod:
          ansible_ssh_private_key_file: /Users/eugene/Dropbox/Eugene/Backups/agile-practices-dev.pem #TODO Set path to private key .pem file for Pre-prod host
          ansible_host: 84.201.157.139 #TODO Set Pre-prod hosting hostname
          ansible_user: admin #TODO Set Pre-prod host username for Ansible provisioning
